version: '3.8'

services:
  frontend:
    build: ./apps/frontend
    container_name: hr-screening-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hr-frontend.rule=Host(\`app.waiz.cl\`)"
      - "traefik.http.routers.hr-frontend.entrypoints=websecure"
      - "traefik.http.routers.hr-frontend.tls=true"
      - "traefik.http.routers.hr-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.hr-frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=dokploy-network"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
